;;;; SPDX-License-Identifier: AGPL-3.0-or-later

(in-package #:ultimate-tic-tac-toe.tests)

(in-suite :ultimate-tic-tac-toe)

(defun deterministic-room-repository (&rest codes)
  (let ((remaining-codes (copy-list codes)))
    (make-memory-room-repository
     :code-generator (lambda ()
                       (let ((code (pop remaining-codes)))
                         (if code
                             (copy-seq code)
                             (error "No deterministic room codes remain.")))))))

(defun accept-seat (repository code mark token)
  (multiple-value-bind (view acceptedp rejection)
      (claim-seat repository code mark token)
    (is (typep view 'room-view))
    (is (not (null acceptedp)))
    (is (null rejection))
    view))

(defun reject-seat (reason repository code mark token)
  (let (signaled-rejection)
    (multiple-value-bind (view acceptedp rejection)
        (handler-bind ((room-rejected (lambda (condition)
                                        (setf signaled-rejection condition))))
          (claim-seat repository code mark token))
      (is (typep view 'room-view))
      (is (null acceptedp))
      (is (typep rejection 'room-rejected))
      (is (eq rejection signaled-rejection))
      (is (eql reason (room-rejected-reason rejection)))
      view)))

(defun accept-room-move (repository code token revision board cell)
  (multiple-value-bind (view acceptedp rejection)
      (play-room-move repository code token revision board cell)
    (is (typep view 'room-view))
    (is (not (null acceptedp)))
    (is (null rejection))
    view))

(defun reject-room-move (reason repository code token revision board cell)
  (let (signaled-rejection)
    (multiple-value-bind (view acceptedp rejection)
        (handler-bind ((room-rejected (lambda (condition)
                                        (setf signaled-rejection condition))))
          (play-room-move repository code token revision board cell))
      (is (typep view 'room-view))
      (is (null acceptedp))
      (is (typep rejection 'room-rejected))
      (is (eq rejection signaled-rejection))
      (is (eql reason (room-rejected-reason rejection)))
      view)))

(test room-creation-produces-watchable-room-with-short-code
  (let* ((repository (deterministic-room-repository "ABCD23"))
         (view (create-room repository)))
    (is (typep view 'room-view))
    (is (string= "ABCD23" (room-view-code view)))
    (is (= 0 (room-view-revision view)))
    (is (eql :watcher (room-view-role view)))
    (is (null (room-view-mark view)))
    (is (room-view-seat-open-p view :x))
    (is (room-view-seat-open-p view :o))
    (is (eql :x (game-next-player (room-view-game view))))))

(test seat-claims-assign-private-token-authority
  (let* ((repository (deterministic-room-repository "ROOM01"))
         (room (create-room repository))
         (code (room-view-code room)))
    (let ((x-view (accept-seat repository code :x "x-token")))
      (is (= 1 (room-view-revision x-view)))
      (is (eql :player (room-view-role x-view)))
      (is (eql :x (room-view-mark x-view)))
      (is (not (room-view-seat-open-p x-view :x)))
      (is (room-view-seat-open-p x-view :o)))
    (let ((x-view (claim-seat repository code :x "x-token")))
      (is (= 1 (room-view-revision x-view)))
      (is (eql :x (room-view-mark x-view))))
    (let ((watcher-view (reject-seat :seat-occupied repository code :x "other-token")))
      (is (eql :watcher (room-view-role watcher-view)))
      (is (null (room-view-mark watcher-view))))
    (let ((x-view (reject-seat :already-seated repository code :o "x-token")))
      (is (eql :player (room-view-role x-view)))
      (is (eql :x (room-view-mark x-view))))
    (let ((o-view (accept-seat repository code :o "o-token")))
      (is (= 2 (room-view-revision o-view)))
      (is (eql :player (room-view-role o-view)))
      (is (eql :o (room-view-mark o-view)))
      (is (not (room-view-seat-open-p o-view :x)))
      (is (not (room-view-seat-open-p o-view :o))))))

(test watchers-and-wrong-seat-cannot-move
  (let* ((repository (deterministic-room-repository "ROOM02"))
         (code (room-view-code (create-room repository))))
    (accept-seat repository code :x "x-token")
    (let ((ready-view (accept-seat repository code :o "o-token")))
      (is (= 2 (room-view-revision ready-view))))
    (let ((watcher-view (reject-room-move :watcher repository code nil 2 0 0)))
      (is (= 2 (room-view-revision watcher-view)))
      (is (null (mark-at (room-view-game watcher-view) 0 0))))
    (let ((o-view (reject-room-move :wrong-turn repository code "o-token" 2 0 0)))
      (is (= 2 (room-view-revision o-view)))
      (is (null (mark-at (room-view-game o-view) 0 0))))
    (let ((x-view (accept-room-move repository code "x-token" 2 0 0)))
      (is (= 3 (room-view-revision x-view)))
      (is (eql :x (mark-at (room-view-game x-view) 0 0)))
      (is (eql :o (game-next-player (room-view-game x-view))))
      (is (= 0 (game-active-board (room-view-game x-view)))))))

(test stale-revisions-and-game-rejections-do-not-mutate-rooms
  (let* ((repository (deterministic-room-repository "ROOM03"))
         (code (room-view-code (create-room repository))))
    (accept-seat repository code :x "x-token")
    (accept-seat repository code :o "o-token")
    (accept-room-move repository code "x-token" 2 0 0)
    (let ((stale-view (reject-room-move :stale-revision repository code "o-token" 2 0 1)))
      (is (= 3 (room-view-revision stale-view)))
      (is (null (mark-at (room-view-game stale-view) 0 1))))
    (let ((wrong-board-view (reject-room-move :wrong-board repository code "o-token" 3 1 1)))
      (is (= 3 (room-view-revision wrong-board-view)))
      (is (null (mark-at (room-view-game wrong-board-view) 1 1))))))

(test unknown-rooms-and-invalid-seats-are-rejected
  (let ((repository (deterministic-room-repository "ROOM04")))
    (multiple-value-bind (view acceptedp rejection)
        (handler-bind ((room-rejected (lambda (condition)
                                        (declare (ignore condition)))))
          (claim-seat repository "MISSING" :x "x-token"))
      (is (null view))
      (is (null acceptedp))
      (is (typep rejection 'room-rejected))
      (is (eql :room-not-found (room-rejected-reason rejection))))
    (let* ((code (room-view-code (create-room repository)))
           (view (reject-seat :invalid-seat repository code :z "z-token")))
      (is (eql :watcher (room-view-role view))))))

(test missing-seat-tokens-do-not-claim-seats
  (let* ((repository (deterministic-room-repository "ROOM06"))
         (code (room-view-code (create-room repository)))
         (nil-token-view (reject-seat :missing-token repository code :x nil)))
    (is (= 0 (room-view-revision nil-token-view)))
    (is (eql :watcher (room-view-role nil-token-view)))
    (is (room-view-seat-open-p nil-token-view :x))
    (let ((empty-token-view (reject-seat :missing-token repository code :o "")))
      (is (= 0 (room-view-revision empty-token-view)))
      (is (eql :watcher (room-view-role empty-token-view)))
      (is (room-view-seat-open-p empty-token-view :o)))))

(test room-views-do-not-expose-mutable-room-state
  (let* ((repository (deterministic-room-repository "ROOM05"))
         (code (room-view-code (create-room repository)))
         (view (accept-seat repository code :x "x-token"))
         (game-copy (room-view-game view)))
    (setf (aref (game-cells game-copy) 0 0) :x)
    (let ((fresh-view (claim-seat repository code :x "x-token")))
      (is (null (mark-at (room-view-game fresh-view) 0 0)))
      (is (= 1 (room-view-revision fresh-view))))))

(test room-views-do-not-expose-mutable-room-codes
  (let* ((repository (deterministic-room-repository "ROOM07"))
         (view (create-room repository))
         (code (room-view-code view))
         (lookup-code (copy-seq code)))
    (setf (aref code 0) #\X)
    (let ((fresh-view (accept-seat repository lookup-code :x "x-token")))
      (is (string= lookup-code (room-view-code fresh-view)))
      (is (= 1 (room-view-revision fresh-view))))))

(defun temporary-room-database-path ()
  (merge-pathnames (make-pathname :name (format nil "uttt-room-~A" (gensym))
                                  :type "sqlite3")
                   (uiop:temporary-directory)))

(defmacro with-temporary-room-database ((path) &body body)
  `(let ((,path (temporary-room-database-path)))
     (unwind-protect
          (progn ,@body)
       (when (probe-file ,path)
         (delete-file ,path)))))

(defun deterministic-sqlite-room-repository (path &rest codes)
  (let ((maker (find-symbol "MAKE-SQLITE-ROOM-REPOSITORY"
                            :ultimate-tic-tac-toe.rooms))
        (remaining-codes (copy-list codes)))
    (unless (and maker (fboundp maker))
      (error "SQLite room repository constructor is not available."))
    (funcall maker
             path
             :code-generator (lambda ()
                               (let ((code (pop remaining-codes)))
                                 (if code
                                     (copy-seq code)
                                     (error "No deterministic room codes remain.")))))))

(test sqlite-room-repository-persists-room-across-reopen
  (with-temporary-room-database (path)
    (let* ((repository (deterministic-sqlite-room-repository path "SQL001"))
           (created (create-room repository))
           (code (room-view-code created)))
      (accept-seat repository code :x "x-token")
      (accept-seat repository code :o "o-token")
      (let ((x-view (accept-room-move repository code "x-token" 2 0 0)))
        (is (= 3 (room-view-revision x-view)))
        (is (eql :x (mark-at (room-view-game x-view) 0 0))))
      (let* ((reopened (deterministic-sqlite-room-repository path "UNUSED"))
             (x-view (view-room reopened code "x-token")))
        (is (= 3 (room-view-revision x-view)))
        (is (eql :player (room-view-role x-view)))
        (is (eql :x (room-view-mark x-view)))
        (is (not (room-view-seat-open-p x-view :x)))
        (is (not (room-view-seat-open-p x-view :o)))
        (is (eql :x (mark-at (room-view-game x-view) 0 0)))
        (is (eql :o (game-next-player (room-view-game x-view))))))))

(test sqlite-room-repository-rejects-stale-move-after-reopen
  (with-temporary-room-database (path)
    (let* ((repository (deterministic-sqlite-room-repository path "SQL002"))
           (code (room-view-code (create-room repository))))
      (accept-seat repository code :x "x-token")
      (accept-seat repository code :o "o-token")
      (accept-room-move repository code "x-token" 2 0 0)
      (let* ((reopened (deterministic-sqlite-room-repository path "UNUSED"))
             (stale-view (reject-room-move :stale-revision
                                           reopened
                                           code
                                           "o-token"
                                           2
                                           0
                                           1)))
        (is (= 3 (room-view-revision stale-view)))
        (is (null (mark-at (room-view-game stale-view) 0 1)))))))
